sudo: required

language: python

python:
  - "3.5"

branches:
  only:
    - master

env:
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='lms+discovery+forum'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='lms+marketing'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='lms+registrar'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='ecommerce'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='edx_notes_api'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='credentials'
  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='analytics_pipeline'

services:
  - docker

before_install:
  # Upgrade Docker to the latest version
  - docker version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - docker-compose --version

  - make requirements
  - make dev.clone
  - |
    if [[ $DEVSTACK == 'lms+marketing' ]]; then
        make dev.pull.lms
    else
        make dev.pull.${DEVSTACK}
    fi

script:
  - "./.travis/run.sh"
